spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  application:
    name: zjjhyzd-blog
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.202.112:3306/blog?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    com.zjjhyzd.blog: DEBUG
server:
  servlet:
    context-path: /api
  port: 8080
user:
  autograph: 我爱学习，学习爱我
  githubUrl: https://github.com/172115637
  headimg: https://avatars1.githubusercontent.com/u/14285531?v=4
  nickname: lizhixiang
  password: 123456
  qrCodeUrl: https://www.17sucai.com/preview/177065/2017-09-28/Mon9/static/img/qq-group.jpg
  username: admin
  weiboUrl: /
aliyun:
  oss:
    access-key: LTAI62tV1Ikh6vM5
    secret-key: ioSSkSJrRuNSaar94A61fq7LCWB51x
    endpoint: oss-cn-shenzhen.aliyuncs.com
    bucket-name: lizhixiang
    base-path: www/blog
    domain: http://blog.zjjhyzd.com
temp:
  path: E:\temp